name: Build and publish Mina lightweight network Docker images
on:
  push:
    branches: ['**']
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch: {}
jobs:
  build-and-publish-amd64:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker images (amd64)
        run: ./scripts/build-all.sh --mina-release nightly --target-branches develop,compatible,master --archs amd64 --docker-hub-user o1labs --extra-docker-suffix experimental --skip-push
  build-and-publish-arm64:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker images (arm64)
        run: ./scripts/build-all.sh --mina-release nightly --target-branches develop,compatible,master --archs arm64 --docker-hub-user o1labs --extra-docker-suffix experimental --skip-push

