name: Build and publish Mina lightweight network Docker images
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Install and cache Hetzner Cloud CLI
        uses: 3bit/setup-hcloud@v2
      - name: Create mina-build-system cloud VM
        run: hcloud server create --name mina-build-system --datacenter fsn1-dc14 --primary-ipv4 35577977 --image 132107836 --type cpx31 --ssh-key app@localhost --start-after-create
        env:
          HCLOUD_TOKEN: ${{ secrets.HETZNER_API_TOKEN }}
      - name: Sleep for 120 seconds
        run: sleep 120s
        shell: bash
      - name: Update remote repositories
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.MINA_BUILD_SYSTEM_IP }}
          username: ${{ secrets.MINA_BUILD_SYSTEM_SSH_USER_NAME }}
          key: ${{ secrets.MINA_BUILD_SYSTEM_SSH_PRIVATE_KEY }}
          script: bash -ilc "${HOME}/projects/git-pull-all.sh"
          command_timeout: 170m
      - name: Build and publish Docker images (major branches)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.MINA_BUILD_SYSTEM_IP }}
          username: ${{ secrets.MINA_BUILD_SYSTEM_SSH_USER_NAME }}
          key: ${{ secrets.MINA_BUILD_SYSTEM_SSH_PRIVATE_KEY }}
          script: bash -ilc "${HOME}/projects/o1labs/mina-lightnet-docker/scripts/build-all.sh ${HOME}/projects/o1labs/mina ${HOME}/projects/o1labs/Archive-Node-API ${HOME}/projects/o1labs/mina-lightnet-docker ${HOME}/projects/p42/mina-accounts-manager o1labs \"develop berkeley rampup\""
          command_timeout: 170m
      - name: Sleep for 15 seconds
        run: sleep 15s
        shell: bash
      - name: Power off the VM
        run: hcloud server poweroff mina-build-system
        env:
          HCLOUD_TOKEN: ${{ secrets.HETZNER_API_TOKEN }}
      - name: Sleep for 15 seconds
        run: sleep 15s
        shell: bash
      - name: Delete the VM
        run: hcloud server delete mina-build-system
        env:
          HCLOUD_TOKEN: ${{ secrets.HETZNER_API_TOKEN }}
      - name: Sleep for 15 seconds
        run: sleep 15s
        shell: bash
