name: Build and publish Mina lightweight network Docker images
on:
  workflow_dispatch: {}
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build Docker images and push to Docker Hub
        run: ./scripts/build-all.sh --mina-release nightly --target-branches develop,compatible,master --archs amd64,arm64 --docker-hub-user o1labs --extra-docker-suffix experimental